name: Cross-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          pkg: cmd/lokidb
          dest: dist
          prefix: lokidb
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          buildmode: default

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            dist
